### ISSUE TITLE
input path should probably more generic

### ISSUE THREAD

**Issue by Narrat** [maltesa/Rofi-Leo-Dictionary#1]
Looking at https://github.com/maltesa/Rofi-Leo-Dictionary/blob/master/leo_search_rofi.sh#L26

The path were it looks for the ruby file is hardcoded.
So, two choices
 1) Adjust README.md, with before running the scripts, adjust the path
 2) Make the path more generic

Kinda like

``` diff
diff --git a/leo_search_rofi.sh b/leo_search_rofi.sh
index adf0eb8..44bfb4e 100755
--- a/leo_search_rofi.sh
+++ b/leo_search_rofi.sh
@@ -22,6 +22,7 @@ if [[ -z "$input" ]]; then
 fi

 # Call search script as long as there is input
+SEARCH_RB="."
 while [ -n "$input" ]; do
-  input=$( ruby /home/malte/Skripte\ und\ Anwendungen/leo_search.rb $(echo $input) | rofi -dmenu -l 30 -p "Leo Dict: " | awk '{print $1}' )
+  input=$( ruby ${SEARCH_RB}/leo_search.rb $(echo $input) | rofi -dmenu -l 30 -p "Leo Dict: " | awk '{print $1}' )
 done
\ No newline at end of file
```

**Comment by maltesa** [comment]
thanks, i've changed that :+1:

**Comment by Narrat** [comment]
Shiny. Now it should be more obvious that there is something what should be adjusted.

Although I would have set a default value (current dir) because if people clone the repo (or download the files manually) they're probably in the same location (Download dir, user binary dir).

Nonetheless I will close this issue
