### ISSUE TITLE
undefined method `encode' for URI:Module

### ISSUE THREAD

**Issue by agaAdams** [maltesa/Rofi-Leo-Dictionary#2]
Recently I am getting this error with leo search rofi:

```leo_search.rb:39:in `<main>': undefined method `encode' for URI:Module (NoMethodError)```

Any suggestions what might be causing this?

**Comment by maltesa** [comment]
I guess, that happens because `URI.encode` was deprecated and was finally removed in the latest ruby versions. I updated the ruby code which should fix the issue.
